// Auto-generated by scripts/generate_version.sh. Do not edit manually.
import Foundation

enum AppVersion {
    static let version = "1.0.0"
    static let build = "8"
    static let gitCommit = "a8a109b"
    static let generatedAt = "2026-06-19T19:57:57Z"
    static let display = "v\(version) (Build \(build))"
    static let detail = "v\(version) (Build \(build), \(gitCommit))"
}
