// Auto-generated by scripts/generate_version.sh. Do not edit manually.
import Foundation

enum AppVersion {
    static let version = "1.0.0"
    static let build = "7"
    static let gitCommit = "d54b710"
    static let generatedAt = "2026-06-19T19:55:13Z"
    static let display = "v\(version) (Build \(build))"
    static let detail = "v\(version) (Build \(build), \(gitCommit))"
}
