#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""九联光猫获取超级密码工具 v1.0 - 后端 helper。
从 stdin 读取 JSON 参数，stdout 输出 JSON 结果。GUI 不显示核心技术细节。
"""

import base64
import json
import os
import pathlib
import re
import socket
import sys
import time
import traceback
from datetime import datetime

REMOTE_ENCRYPTED_FILE = "/config/workb/backup_lastgood.xml"
REMOTE_DECRYPT_SCRIPT = "/home/cli/decrypt/decrypt_file"
DEBUG_LOG_DIR = pathlib.Path.home() / "Library/Application Support/local.jiulian.superpassword/Logs"
DEBUG_LOG_FILE = DEBUG_LOG_DIR / "backend_debug.log"
ANSI_RE = re.compile(rb"\x1b\[[0-9;]*[A-Za-z]")
STREAM = False


VENDOR_DIR = pathlib.Path(__file__).resolve().parent / "vendor"
if VENDOR_DIR.exists():
    sys.path.insert(0, str(VENDOR_DIR))

try:
    from telnetlib_compat import Telnet
except Exception as e:
    raise RuntimeError(f"程序资源缺失：telnetlib_compat.py，无法连接光猫：{e}")


def emit(obj):
    if STREAM:
        try:
            print(json.dumps(obj, ensure_ascii=False), flush=True)
        except BrokenPipeError:
            # 前端提前断开时不要污染设备流程/调试输出
            pass


def debug(title, detail):
    try:
        DEBUG_LOG_DIR.mkdir(parents=True, exist_ok=True)
        with DEBUG_LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(f"\n[{datetime.now().isoformat(timespec='seconds')}] {title}\n")
            f.write(str(detail))
            f.write("\n")
        try:
            os.chmod(DEBUG_LOG_FILE, 0o600)
        except Exception:
            pass
    except Exception:
        pass


def log(logs, msg, level="info"):
    item = {"time": datetime.now().strftime("%H:%M:%S"), "message": msg, "level": level}
    logs.append(item)
    emit({"type": "log", **item})


def elapsed_since(start):
    return f"{time.perf_counter() - start:.1f} 秒"


def human_bytes(size):
    size = int(size or 0)
    if size < 1024:
        return f"{size} B"
    if size < 1024 * 1024:
        return f"{size / 1024:.1f} KB"
    return f"{size / 1024 / 1024:.1f} MB"


def strip_ansi(data):
    return ANSI_RE.sub(b"", data)


def read_some(tn, quiet=2.0, hard=None):
    quiet_end = time.time() + quiet
    hard_end = time.time() + (hard if hard is not None else max(quiet + 2.0, 3.0))
    data = b""
    while time.time() < quiet_end and time.time() < hard_end:
        try:
            chunk = tn.read_very_eager()
            if chunk:
                data += chunk
                quiet_end = time.time() + 0.4
            else:
                time.sleep(0.08)
        except socket.timeout:
            time.sleep(0.08)
        except EOFError:
            break
    return data


def run_cmd(tn, cmd, wait=1.0, timeout=8.0):
    marker = f"__OC_MARK_{int(time.time() * 1000)}__"
    end_marker = marker + "_END"
    full_cmd = f"echo {marker}; {cmd}; echo __RET__$?; echo {end_marker}\n"
    tn.write(full_cmd.encode())
    time.sleep(wait)
    out = read_some(tn, quiet=timeout, hard=timeout + 3.0)
    if end_marker.encode() not in out:
        out += read_some(tn, quiet=2.0, hard=3.0)
    text = strip_ansi(out).decode("latin1", errors="replace")
    if end_marker not in text:
        debug("remote command timeout", {"cmd": cmd, "tail": text[-2000:]})
        raise RuntimeError("光猫响应超时，请确认连接稳定后重试。")
    return text


def is_our_tmp(path):
    return re.fullmatch(r"/tmp/oclg_[0-9]+_[0-9]+\.dec", path or "") is not None


def cleanup_current_remote_tmp(tn, logs, remote_tmp, wait=0.2, timeout=3.0):
    """Check and clean only the temp file generated by this run."""
    if tn is None:
        log(logs, "步骤 5/5：未连接光猫，未生成本次临时数据，无需清理。")
        return False
    if not is_our_tmp(remote_tmp):
        log(logs, f"步骤 5/5：清理失败，请手动登录光猫 /tmp 目录检查并清理本次临时文件：{remote_tmp}", "error")
        debug("skip cleanup unsafe tmp path", {"remote_tmp": remote_tmp})
        return False

    log(logs, f"步骤 5/5：正在清理临时文件 {remote_tmp} …")
    try:
        text = run_cmd(
            tn,
            f"if [ -f {remote_tmp} ]; then "
            f"rm -f {remote_tmp}; "
            f"if [ -f {remote_tmp} ]; then echo __OC_CLEAN_FAILED__; else echo __OC_CLEANED__; fi; "
            f"else echo __OC_NO_TMP__; fi",
            wait=wait,
            timeout=timeout,
        )
    except Exception as cleanup_error:
        debug("cleanup current remote tmp failed", {"remote_tmp": remote_tmp, "error": repr(cleanup_error)})
        log(logs, f"步骤 5/5：清理失败，请手动登录光猫 /tmp 目录删除本次临时文件：{remote_tmp}", "error")
        return False

    if "__OC_CLEANED__" in text:
        log(logs, f"步骤 5/5：已清理临时文件 {remote_tmp}。")
        return True
    if "__OC_NO_TMP__" in text:
        log(logs, f"步骤 5/5：临时文件 {remote_tmp} 未生成，无需清理。")
        return True

    debug("cleanup current remote tmp did not confirm", {"remote_tmp": remote_tmp, "tail": text[-2000:]})
    log(logs, f"步骤 5/5：清理失败，请手动登录光猫 /tmp 目录删除本次临时文件：{remote_tmp}", "error")
    return False


def read_until_bytes(tn, token, hard=120.0, idle_after_data=8.0):
    """Read Telnet output until token appears or a real timeout occurs.

    `read_some()` is quiet-window based and is good for short command output.
    Large base64 transfers can pause between chunks on real devices, so this
    path waits for an explicit end marker instead of returning after a short
    quiet gap.
    """
    token = token if isinstance(token, bytes) else str(token).encode()
    data = b""
    start_at = time.time()
    last_data_at = None
    while time.time() - start_at < hard:
        try:
            chunk = tn.read_very_eager()
        except socket.timeout:
            chunk = b""
        except EOFError:
            break
        if chunk:
            data += chunk
            last_data_at = time.time()
            if token in data:
                return data
            continue
        if last_data_at is not None and time.time() - last_data_at >= idle_after_data:
            return data
        time.sleep(0.08)
    return data


def fetch_remote_file_base64(tn, remote_path):
    start = "__OC_B64_BEGIN__"
    end = "__OC_B64_END__"
    # Use echo rather than printf for better compatibility with minimal embedded shells.
    tn.write(f"echo {start}; base64 {remote_path}; echo {end}\n".encode())
    cap = read_until_bytes(tn, end.encode(), hard=120.0, idle_after_data=8.0)
    if end.encode() not in cap:
        clean = strip_ansi(cap)
        debug("fetch timeout", {
            "remote_path": remote_path,
            "received_bytes": len(cap),
            "has_begin_marker": start.encode() in clean,
            "has_end_marker": end.encode() in clean,
            "base64_like_line_count": sum(1 for line in clean.splitlines() if re.fullmatch(rb"[A-Za-z0-9+/=]{8,}", line.strip())),
        })
        raise RuntimeError("传回结果超时，请重试。")

    cap = strip_ansi(cap)
    collecting = False
    b64_lines = []
    for line in cap.splitlines():
        s = line.strip()
        if s == start.encode():
            collecting = True
            continue
        if s == end.encode():
            break
        if collecting and re.fullmatch(rb"[A-Za-z0-9+/=]{8,}", s):
            b64_lines.append(s)
    if not b64_lines:
        debug("fetch empty", {
            "received_bytes": len(cap),
            "has_begin_marker": start.encode() in cap,
            "has_end_marker": end.encode() in cap,
        })
        raise RuntimeError("没有收到有效结果数据，请重试。")
    try:
        return base64.b64decode(b"".join(b64_lines))
    except Exception as e:
        debug("base64 decode failed", {"error": repr(e), "lines": len(b64_lines)})
        raise RuntimeError("结果数据校验失败，请重试。")

def parse_value(xml_text, name):
    pattern = rf'<Value\s+Name="{re.escape(name)}"\s+Value="([^"]*)"'
    m = re.search(pattern, xml_text)
    return m.group(1) if m else ""


def run(params):
    logs = []
    total_start = time.perf_counter()
    host = str(params.get("host", "")).strip()
    port = int(str(params.get("port", "23")).strip() or "23")
    user = str(params.get("user", "")).strip()
    password = str(params.get("password", ""))
    output_dir = pathlib.Path(str(params.get("output_dir", str(pathlib.Path.home() / "Downloads")))).expanduser()
    clean_tmp = bool(params.get("clean_tmp", True))

    if not host:
        raise ValueError("请填写光猫 IP。")
    if not user:
        raise ValueError("请填写登录用户名。")
    if not password:
        raise ValueError("请填写登录密码。")
    output_dir.mkdir(parents=True, exist_ok=True)

    tn = None
    remote_tmp = f"/tmp/oclg_{int(time.time())}_{os.getpid()}.dec"
    step5_done = False
    try:
        step_start = time.perf_counter()
        log(logs, "步骤 1/5：正在连接光猫…")
        last_connect_error = None
        for attempt in range(1, 4):
            try:
                tn = Telnet(host, port, timeout=8)
                try:
                    tn.get_socket().settimeout(0.5)
                except Exception:
                    pass
                break
            except Exception as e:
                last_connect_error = e
                if attempt < 3:
                    log(logs, f"连接暂时无响应，正在重试 {attempt}/2…")
                    time.sleep(1.5)
                else:
                    raise RuntimeError(f"连接光猫失败：{e}")
        if tn is None:
            raise RuntimeError(f"连接光猫失败：{last_connect_error}")

        banner = tn.read_until(b"login:", timeout=6)
        if b"login:" not in banner:
            raise RuntimeError("连接成功但未进入登录流程，请确认光猫登录服务正常。")

        tn.write(user.encode() + b"\n")
        pw_prompt = tn.read_until(b"Password:", timeout=5)
        if b"Password:" not in pw_prompt:
            raise RuntimeError("用户名发送后未进入密码输入流程，请确认用户名正确。")

        tn.write(password.encode() + b"\n")
        time.sleep(1.0)
        out = read_some(tn, quiet=2.0, hard=4.0)
        # 注意：成功后可能输出 "login: can't change directory to '/root'"，不能把 login: 当失败
        if b"incorrect" in out.lower():
            raise RuntimeError("登录失败：用户名或密码不正确。")
        log(logs, f"步骤 1/5：登录成功（用时 {elapsed_since(step_start)}）。")

        try:
            tn.write(b"stty -echo 2>/dev/null\n")
            time.sleep(0.2)
            read_some(tn, quiet=0.5, hard=1.5)
            tn.write(b"export PS1=''\n")
            time.sleep(0.2)
            read_some(tn, quiet=0.5, hard=1.5)
        except Exception:
            pass

        step_start = time.perf_counter()
        log(logs, "步骤 2/5：正在检查设备配置…")
        text = run_cmd(tn, f"[ -f {REMOTE_ENCRYPTED_FILE} ] && echo EXISTS && wc -c {REMOTE_ENCRYPTED_FILE} || echo MISSING", wait=0.5, timeout=4.0)
        if "EXISTS" not in text:
            raise RuntimeError("未找到配置文件，请确认设备型号/固件支持。")
        log(logs, f"步骤 2/5：配置文件检查完成（用时 {elapsed_since(step_start)}）。")

        step_start = time.perf_counter()
        log(logs, "步骤 3/5：正在解析超级密码…")
        cmd = (
            f"rm -f {remote_tmp}; "
            f"cli {REMOTE_DECRYPT_SCRIPT} -v ifile {REMOTE_ENCRYPTED_FILE} ofile {remote_tmp}; "
            f"echo __CHECK_DEC_FILE__; "
            f"if [ -s {remote_tmp} ]; then echo __DEC_OK__; wc -c {remote_tmp}; "
            f"else echo __DEC_MISSING__; ls -l {remote_tmp} 2>&1; fi"
        )
        text = run_cmd(tn, cmd, wait=1.0, timeout=10.0)
        if "succ." not in text:
            debug("decrypt no succ", text)
            raise RuntimeError("解析失败：设备没有返回成功状态。")
        if "__DEC_OK__" not in text:
            debug("decrypt missing output", text)
            raise RuntimeError("解析失败：设备没有生成结果。")
        log(logs, f"步骤 3/5：解析完成（用时 {elapsed_since(step_start)}）。")

        step_start = time.perf_counter()
        log(logs, "步骤 4/5：正在提取必要信息并回传…")

        # 只回传 2 个 Dir 块，大幅减少数据量，避免 Telnet 阻塞/掉线：
        #   - aucTeleAccountPassword 所在的 Dir
        #   - DEVINFO_TAB 块
        filtered_tmp = remote_tmp + ".f"
        # 用 awk 按嵌套深度提取 3 个目标 Dir 块。
        # 兼容 busybox awk：显式赋值、$0 ~ /re/ 语法、BEGIN 初始化 depth。
        awk_script = (
            'BEGIN { depth = 0 }\n'
            '/<Dir[ >]/ {\n'
            '  depth = depth + 1\n'
            '  bufs[depth] = $0 "\\n"\n'
            '  keeps[depth] = 0\n'
            '  if ($0 ~ /aucTeleAccountPassword|DEVINFO_TAB/) keeps[depth] = 1\n'
            '  next\n'
            '}\n'
            '/<\\/Dir>/ {\n'
            '  bufs[depth] = bufs[depth] $0 "\\n"\n'
            '  if (keeps[depth] == 1) printf "%s", bufs[depth]\n'
            '  depth = depth - 1\n'
            '  next\n'
            '}\n'
            '{\n'
            '  if (depth > 0) {\n'
            '    bufs[depth] = bufs[depth] $0 "\\n"\n'
            '    if ($0 ~ /aucTeleAccountPassword|DEVINFO_TAB/) keeps[depth] = 1\n'
            '  }\n'
            '}\n'
        )
        filter_cmd = (
            f"awk '{awk_script}' {remote_tmp}"
            f" > {filtered_tmp}"
            f"; echo __OC_FILTER_DONE__"
            f"; wc -c {filtered_tmp}"
        )
        # 先尝试 awk 过滤，检查结果非空防止 awk 静默失败
        use_filtered = False
        try:
            run_cmd(tn, filter_cmd, wait=0.5, timeout=8.0)
            check_cmd = f"[ -s {filtered_tmp} ] && echo __OC_FILTER_OK__ || echo __OC_FILTER_EMPTY__"
            check_text = run_cmd(tn, check_cmd, wait=0.2, timeout=3.0)
            if "__OC_FILTER_OK__" in check_text:
                use_filtered = True
            else:
                debug("filter xml produced empty output", {"check_text": check_text[-500:]})
                log(logs, "步骤 4/5：awk 过滤未产生有效输出，回退完整配置文件…")
        except Exception as filter_err:
            debug("filter xml failed", {"error": repr(filter_err)})
            log(logs, "步骤 4/5：过滤 XML 失败，正在回传完整配置文件…")

        if not use_filtered:
            run_cmd(tn, f"cp {remote_tmp} {filtered_tmp}", wait=0.2, timeout=3.0)

        xml_bytes = fetch_remote_file_base64(tn, filtered_tmp)
        run_cmd(tn, f"rm -f {filtered_tmp}", wait=0.2, timeout=3.0)

        fetch_elapsed = elapsed_since(step_start)
        xml_text = xml_bytes.decode("utf-8", errors="replace")
        super_account = parse_value(xml_text, "aucTeleAccountName")
        super_password = parse_value(xml_text, "aucTeleAccountPassword")
        if not super_account and not super_password:
            raise RuntimeError("未找到超级管理员账号/密码。")

        emit({"type": "credentials", "super_account": super_account or "", "super_password": super_password or ""})

        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_host = re.sub(r"[^0-9A-Za-z_.-]", "_", host)
        out_file = output_dir / f"jiulian_super_password_{safe_host}_{ts}.xml"
        out_file.write_bytes(xml_bytes)
        if use_filtered:
            log(logs, f"步骤 4/5：结果已保存，仅回传必要 Dir 块（接收 {human_bytes(len(xml_bytes))}，用时 {fetch_elapsed}）。")
        else:
            log(logs, f"步骤 4/5：结果已保存，接收 {human_bytes(len(xml_bytes))}（用时 {fetch_elapsed}）。")

        if clean_tmp:
            if cleanup_current_remote_tmp(tn, logs, remote_tmp, wait=0.5, timeout=4.0):
                remote_tmp = ""
        else:
            log(logs, "步骤 5/5：已按设置保留本次临时数据。")
        step5_done = True

        log(logs, f"完成：已成功获取超级密码（总用时 {elapsed_since(total_start)}）。", "success")
        return {"ok": True, "logs": logs, "super_account": super_account or "未找到", "super_password": super_password or "未找到", "output_file": str(out_file)}
    finally:
        if tn is not None:
            try:
                if not step5_done:
                    if clean_tmp:
                        cleaned = cleanup_current_remote_tmp(tn, logs, remote_tmp, wait=0.2, timeout=2.0)
                        if not cleaned:
                            # 当前 Telnet 可能已断开。
                            # 网络阻塞后恢复需要时间，不能立刻重连。
                            try:
                                tn.close()
                            except Exception:
                                pass
                            reconnect_ok = False
                            for retry in range(1, 4):
                                wait_sec = retry * 5  # 5s / 10s / 15s 逐次退避
                                log(logs, f"步骤 5/5：等待 {wait_sec} 秒后重试清理（第 {retry}/3 次）…")
                                time.sleep(wait_sec)
                                tn2 = None
                                try:
                                    tn2 = Telnet(host, port, timeout=8)
                                    tn2.read_until(b"login:", timeout=6)
                                    tn2.write(user.encode() + b"\n")
                                    tn2.read_until(b"Password:", timeout=5)
                                    tn2.write(password.encode() + b"\n")
                                    time.sleep(0.8)
                                    read_some(tn2, quiet=2.0, hard=4.0)
                                    tn2.write(b"stty -echo 2>/dev/null\n")
                                    time.sleep(0.2)
                                    read_some(tn2, quiet=0.5, hard=1.5)
                                    tn2.write(b"export PS1=''\n")
                                    time.sleep(0.2)
                                    read_some(tn2, quiet=0.5, hard=1.5)
                                    if cleanup_current_remote_tmp(tn2, logs, remote_tmp, wait=0.2, timeout=2.0):
                                        reconnect_ok = True
                                    tn2.write(b"exit\n")
                                    tn2.close()
                                    if reconnect_ok:
                                        break
                                except Exception:
                                    if tn2:
                                        try:
                                            tn2.close()
                                        except Exception:
                                            pass
                            if not reconnect_ok:
                                log(logs, f"步骤 5/5：3 次重试均失败，请手动登录光猫 /tmp 目录删除本次临时文件：{remote_tmp}", "error")
                    else:
                        log(logs, "步骤 5/5：已按设置保留本次临时数据。")
                tn.write(b"exit\n")
                tn.close()
            except Exception:
                pass


def main():
    global STREAM
    try:
        params = json.loads(sys.stdin.read() or "{}")
        STREAM = bool(params.get("stream"))
        result = run(params)
        if STREAM:
            final = {k: v for k, v in result.items() if k != "logs"}
            final["type"] = "result"
            emit(final)
        else:
            print(json.dumps(result, ensure_ascii=False))
    except Exception as e:
        debug("backend failed", traceback.format_exc())
        logs = []
        log(logs, f"FAIL: {e}", "error")
        log(logs, "请检查光猫 IP、登录用户名/密码、网络连接，确认设备在线后重试。", "error")
        result = {"ok": False, "logs": logs, "error": str(e)}
        if STREAM:
            emit({"type": "result", "ok": False, "error": str(e)})
        else:
            print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
