#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VERSION_FILE="$ROOT/VERSION"
BUILD_FILE="$ROOT/BUILD_NUMBER"
OUT_FILE="$ROOT/Sources/JiulianSuperPasswordTool/GeneratedVersion.swift"

if [[ ! -f "$VERSION_FILE" ]]; then
  echo "1.0.0" > "$VERSION_FILE"
fi
if [[ ! -f "$BUILD_FILE" ]]; then
  echo "1" > "$BUILD_FILE"
fi

VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
BUILD="$(tr -d '[:space:]' < "$BUILD_FILE")"
if [[ -z "$VERSION" ]]; then VERSION="1.0.0"; fi
if ! [[ "$BUILD" =~ ^[0-9]+$ ]]; then BUILD="1"; fi

GIT_COMMIT="unknown"
if git -C "$ROOT" rev-parse --short HEAD >/dev/null 2>&1; then
  GIT_COMMIT="$(git -C "$ROOT" rev-parse --short HEAD)"
fi
GENERATED_AT="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

cat > "$OUT_FILE" <<SWIFT
// Auto-generated by scripts/generate_version.sh. Do not edit manually.
import Foundation

enum AppVersion {
    static let version = "$VERSION"
    static let build = "$BUILD"
    static let gitCommit = "$GIT_COMMIT"
    static let generatedAt = "$GENERATED_AT"
    static let display = "v\(version) (Build \(build))"
    static let detail = "v\(version) (Build \(build), \(gitCommit))"
}
SWIFT

echo "Generated $OUT_FILE: v$VERSION (Build $BUILD, $GIT_COMMIT)"
