// Auto-generated by scripts/generate_version.sh. Do not edit manually.
import Foundation

enum AppVersion {
    static let version = "1.0.2"
    static let build = "18"
    static let gitCommit = "c383de1"
    static let generatedAt = "2026-06-20T04:33:52Z"
    static let display = "v\(version) (Build \(build))"
    static let detail = "v\(version) (Build \(build), \(gitCommit))"
}
