// Auto-generated by scripts/generate_version.sh. Do not edit manually.
import Foundation

enum AppVersion {
    static let version = "1.0.2"
    static let build = "22"
    static let gitCommit = "7d913e6"
    static let generatedAt = "2026-06-20T06:03:29Z"
    static let display = "v\(version) (Build \(build))"
    static let detail = "v\(version) (Build \(build), \(gitCommit))"
}
